# 1. Setup & import

In [1]:
import pandas as pd
import numpy as np

pd.__ version__  -     check the installed pandas version

In [2]:
pd.__version__

'2.3.3'

# 2. Creating Series & dataFrames

pd. Series( )  - creeate a 1D labeled array

In [3]:
s = pd.Series([10, 20, 30])
s

0    10
1    20
2    30
dtype: int64

In [4]:
s=pd.Series([10, 20, 30], index=['a','b','c'], name='values')
s

a    10
b    20
c    30
Name: values, dtype: int64

pd.DataFrame( ) form a dict of list - create a labeled 2D table

In [5]:
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, 30, 35, 40],
    'city': ['NY', 'LA', 'SF', 'NY']
})
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

pd.DataFrame( ) from a list of dict

In [6]:
pd.DataFrame([{'a':1, 'b':2, }, {'a':3, 'b':4}])

   a  b
0  1  2
1  3  4


pd.DataFrame( )   from a NumPy array

In [7]:
pd.DataFrame(np. arange(6).reshape(2,3),columns=['x','y','z'])

   x  y  z
0  0  1  2
1  3  4  5

# 3.Attributes & Inspection

In [8]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

.shape( ) -  (rows, columns)

In [9]:
df.shape

(4, 3)

.columns( ) - columns labels

In [10]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

.index(  ) - row labels

In [11]:
df.index

RangeIndex(start=0, stop=4, step=1)

.dtypes (  ) data types of each  columns

In [12]:
df.dtypes

name    object
age      int64
city    object
dtype: object

.values(  )    underlining NumPy array

In [13]:
df.values

array([['Alice', 25, 'NY'],
       ['Bob', 30, 'LA'],
       ['Charlie', 35, 'SF'],
       ['David', 40, 'NY']], dtype=object)

.size (  ) total numbers of element

In [14]:
df.size

12

.head(  ) first n rows

In [15]:
df.head(0)

Empty DataFrame
Columns: [name, age, city]
Index: []

In [16]:
df.head(1)

    name  age city
0  Alice   25   NY

In [17]:
df.head(2)

    name  age city
0  Alice   25   NY
1    Bob   30   LA

In [18]:
df.head(3)

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF

In [19]:
df.head(4)

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

.tali( ) last n rows

In [20]:
df.tail(4)

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [21]:
df.tail(3)

      name  age city
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [22]:
df.tail(2)

      name  age city
2  Charlie   35   SF
3    David   40   NY

In [23]:
df.tail(1)

    name  age city
3  David   40   NY

In [24]:
df.tail(0)

Empty DataFrame
Columns: [name, age, city]
Index: []

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
 2   city    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [26]:
df.describe()

             age
count   4.000000
mean   32.500000
std     6.454972
min    25.000000
25%    28.750000
50%    32.500000
75%    36.250000
max    40.000000

In [27]:
df.memory_usage()

Index    132
name      32
age       32
city      32
dtype: int64

# 4.Selection & Indexing(loc, iloc, at, iat)

.set _ index( ) - set a column as the row index

In [28]:
df.set_index('name',inplace=False)

         age city
name
Alice     25   NY
Bob       30   LA
Charlie   35   SF
David     40   NY

Column selection - a single column returns a series

In [29]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [30]:
df['age']

0    25
1    30
2    35
3    40
Name: age, dtype: int64

In [31]:
df[['name','age']]

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

.loc [ ] - select a row by lable

In [32]:
df.loc[0]

name    Alice
age        25
city       NY
Name: 0, dtype: object

In [33]:
df.loc[1]

name    Bob
age      30
city     LA
Name: 1, dtype: object

.loc[ ] - select a scalar value by label

In [34]:
df.loc[0,'age']

np.int64(25)

.loc [  ] - select rows & columns by lable

In [35]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

In [36]:
df.loc[0:2, ['name', 'age']]

      name  age
0    Alice   25
1      Bob   30
2  Charlie   35

.iloc[ ] - select a row by integer position

In [37]:
df.iloc[0]

name    Alice
age        25
city       NY
Name: 0, dtype: object

.iloc[  ] - select a scalar value by  integer

In [38]:
df.iloc[0,1]

np.int64(25)

In [39]:
df.iloc[1,1]

np.int64(30)

.iloc[ ] - select rows & columns by integer position

In [40]:
df. iloc[0:2, 0:2]

    name  age
0  Alice   25
1    Bob   30

In [41]:
df.iloc[0:3, 0:3]

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF

.at [  ] - fast scalar access by lable

In [42]:
df.at[0, 'age']

np.int64(25)

In [43]:
df.at[1, 'name']

'Bob'

In [44]:
df.at[0,'city']

'NY'

.iat[ ] - fast scalar access by integer position

In [45]:
df.iat[0,1]

np.int64(25)

In [46]:
df.iat[1,1]

np.int64(30)

In [47]:
df.iat[1,2]

'LA'

# 5. Adding, Modifying & Dropping Columns/Rows

In [48]:
df2= df.copy()

Adding a new column from an existing one

In [49]:
df2['senior']= df2['age']> 30
df2

      name  age city  senior
0    Alice   25   NY   False
1      Bob   30   LA   False
2  Charlie   35   SF    True
3    David   40   NY    True

In [50]:
df2['age_plus_5']= df2['age']+5
df2

      name  age city  senior  age_plus_5
0    Alice   25   NY   False          30
1      Bob   30   LA   False          35
2  Charlie   35   SF    True          40
3    David   40   NY    True          45

.rename(  ) - rename columns

In [51]:
df2.rename(columns={'city':'locetion'}, inplace= True)
df2

      name  age locetion  senior  age_plus_5
0    Alice   25       NY   False          30
1      Bob   30       LA   False          35
2  Charlie   35       SF    True          40
3    David   40       NY    True          45

. drop(index=...)    -drop a row

In [52]:
df2

      name  age locetion  senior  age_plus_5
0    Alice   25       NY   False          30
1      Bob   30       LA   False          35
2  Charlie   35       SF    True          40
3    David   40       NY    True          45

In [53]:
df2.drop(index = 0, inplace = False)

      name  age locetion  senior  age_plus_5
1      Bob   30       LA   False          35
2  Charlie   35       SF    True          40
3    David   40       NY    True          45

In [54]:
df2.drop (columns = ['age_plus_5'], inplace = True)
df2

      name  age locetion  senior
0    Alice   25       NY   False
1      Bob   30       LA   False
2  Charlie   35       SF    True
3    David   40       NY    True

In [55]:
df2.drop(columns= ['senior'], inplace= True)
df2

      name  age locetion
0    Alice   25       NY
1      Bob   30       LA
2  Charlie   35       SF
3    David   40       NY

 #  6.Handling Missing Data

In [56]:
df_na = pd.DataFrame({'a':[1, np.nan, 3], 'b':[np.nan, 2, 3]})
df_na

     a    b
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0

.isna(  ) - boolean masks of mising values

In [57]:
df_na.isna()

       a      b
0  False   True
1   True  False
2  False  False

.notna( ) -                        opposit of  .isna(  )

In [58]:
df_na.notna()

       a      b
0   True  False
1  False   True
2   True   True

.isnull()  .sum() - count missing values per column

In [59]:
df_na.isnull().sum()

a    1
b    1
dtype: int64

.dropna( )   - drop rows containing any NaN

In [60]:
df_na.dropna(axis =1)

Empty DataFrame
Columns: []
Index: [0, 1, 2]

.fillna( )  - fill missing values with a constant

In [61]:
df_na.fillna(0)

     a    b
0  1.0  0.0
1  0.0  2.0
2  3.0  3.0

.ffill( )  - forward fill missing values

In [62]:
df_na.ffill()

     a    b
0  1.0  NaN
1  1.0  2.0
2  3.0  3.0

.bfill(   )

In [63]:
df_na.bfill()

     a    b
0  1.0  2.0
1  3.0  2.0
2  3.0  3.0

# 7.Sorting & Ranking

In [64]:
df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, 30, 35, 40],
    'city': ['NY', 'LA', 'SF', 'NY']
})
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

.sort_values( ) -sort

In [65]:
df.sort_values('age')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

.sort_values( ) - sort by multiple columns

In [66]:
df.sort_values(['city','age'],ascending=[True, False])

      name  age city
1      Bob   30   LA
3    David   40   NY
0    Alice   25   NY
2  Charlie   35   SF

.sort_index() - sort rows by index

In [67]:
df.sort_index()

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

.rank()

In [68]:
df['age'].rank()

0    1.0
1    2.0
2    3.0
3    4.0
Name: age, dtype: float64

.nlargest()

In [69]:
df.nlargest(2, 'age')

      name  age city
3    David   40   NY
2  Charlie   35   SF

.nsmallest( )

In [70]:
df.nsmallest(2,'age')

    name  age city
0  Alice   25   NY
1    Bob   30   LA

# 8.Aggregation & Ststistics

.sum( ) / .mean( ), / . median( )  - basic aggregations.

In [71]:
df['age'].sum(), df['age'].mean(), df['age']. median()

(np.int64(130), np.float64(32.5), np.float64(32.5))

.std( ) / .var( )   - spread of the data

In [72]:
df['age'].std(), df['age'].var()

(np.float64(6.454972243679028), np.float64(41.666666666666664))

.min( ) / max( )   - smallest / largest value

In [73]:
df['age'].min(), df['age'].max()

(np.int64(25), np.int64(40))

.count()

In [74]:
df['age'].count()

np.int64(4)

.agg ( )   - apply multiple aggriugetion functions at once

In [75]:
df.agg({'age': ['mean','max','min']})

       age
mean  32.5
max   40.0
min   25.0

.corr ( )   - correlation matrix of numeric columns

In [76]:
df.corr(numeric_only=True)

     age
age  1.0

.mode  ( )  - most frequently occuring value

In [77]:
df['city'].mode

<bound method Series.mode of 0    NY
1    LA
2    SF
3    NY
Name: city, dtype: object>

# 9.Groupby Opretions

In [82]:
g = df.groupby('city')

In [83]:
g.size()

city
LA    1
NY    2
SF    1
dtype: int64

In [84]:
g['age'].mean()   #multi

city
LA    30.0
NY    32.5
SF    35.0
Name: age, dtype: float64

In [85]:
g.agg({'age':['mean','sum']})

       age
      mean sum
city
LA    30.0  30
NY    32.5  65
SF    35.0  35

In [86]:
g.apply(lambda x: x['age'].max() - x['age'].min())    #  on a groupby --custom function per group

C:\Users\Soham\AppData\Local\Temp\ipykernel_13076\1904733013.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  g.apply(lambda x: x['age'].max() - x['age'].min())    #  on a groupby --custom function per group

city
LA     0
NY    15
SF     0
dtype: int64

Itrating over group with a for loop

In [102]:
for name,group in g:
    print(name)
    print(group)

LA
  name  age city
1  Bob   30   LA
NY
    name  age city
0  Alice   25   NY
3  David   40   NY
SF
      name  age city
2  Charlie   35   SF

.get_group( )   - retrive a specific grourp

In [103]:
g.get_group('NY')

    name  age city
0  Alice   25   NY
3  David   40   NY

In [104]:
g.get_group('SF')

      name  age city
2  Charlie   35   SF

In [105]:
g.get_group('LA')

  name  age city
1  Bob   30   LA

Input/Output (CSV,Excel,Json)

In [106]:
df

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

.to_csv( )  / pd.read_csv() -Read csv files

In [107]:
df.to_csv('data.csv',index=False)
pd.read_csv('data.csv')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

.to_json( )/ pd.read_json( ) - write and read JSON files.

In [108]:
df.to_json('data.json',orient='records')
pd.read_json('data.json')

      name  age city
0    Alice   25   NY
1      Bob   30   LA
2  Charlie   35   SF
3    David   40   NY

.to_excel ( )/ pd.read_excel( ) write and read excel files (needs openpyx1)

In [109]:
df.to_excel('data.xlsx', index=False)
pd.read_excel('data.xlsx')

ModuleNotFoundError: No module named 'openpyxl'

.to_dict( ) convert a DataFrame to a list of dict

In [111]:
df.to_dict(orient='records')

[{'name': 'Alice', 'age': 25, 'city': 'NY'},
 {'name': 'Bob', 'age': 30, 'city': 'LA'},
 {'name': 'Charlie', 'age': 35, 'city': 'SF'},
 {'name': 'David', 'age': 40, 'city': 'NY'}]

In [116]:
pd.DataFrame.from_dict({'a':[1,2]})

   a
0  1
1  2